easy_admin:
    site_name: 'Timeout.hr'
    design:
        brand_color: 'rgba(34, 96, 212)'
        menu:
            - { label: 'Timeout'}
            - { entity: 'Centar', icon: 'building' }
            - { entity: 'Teren', icon: 'database' }
            - { entity: 'Sport', icon: 'futbol' }
            
            - { label: 'Settings' }
            - { entity: 'Korisnik', icon: 'user'}
            - { label: 'Timeout', url: 'https://timeout.hr', rel: 'noreferrer', icon: 'globe-africa'}
    formats:
        date: 'd.m.Y'
        time: 'H:i'
        datetime: 'd.m.Y H:i:s'
    user:
        display_avatar: false
    
    entities:
        Centar:
            class: Timeout\Domain\Center\Center
            search:
                fields: ['id', 'name', 'email', 'slug', 'facilities']
            form:
                fields:
                    - { type: 'section', label: 'General'}
                    - 'name'
                    - 'slug'
                    - { property: 'description', type: 'text_editor' }
                    - { type: 'section', label: 'Contact'}
                    - { property: 'email', type: 'email', label: 'Email' }
                    - { property: 'phone', type: 'tel' }
                    - 'address'
                    - { type: 'section', label: 'Working hours'}
                    - 'workingHours'
                    - { type: 'section', label: 'Courts'}
                    - 'courts'
                new:
                edit:
            list:
                fields:
                    - 'id'
                    - 'name'
                    - 'slug'
                    - { property: 'email', type: 'email'}
                    - { property: 'phone', type: 'tel' }
                    - { property: 'courts', type: 'association'}
                    - { property: 'createdAt', type: 'date' }
                filters: ['name', 'slug']
        Teren:
            class: Timeout\Domain\Center\Court
        Sport:
            class: Timeout\Domain\Sport\Sport
        Korisnik:
            class: Timeout\App\User\User
