version: '3.6'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: timeout/php
    container_name: timeout_php
    ports:
      - "8000:80"
    volumes:
      - .:/app:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      COMPOSER_ALLOW_XDEBUG: "true"
  mysql:
    image: mysql
    volumes:
      - ./var/data/db:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timeout
      MYSQL_USER: timeout
      MYSQL_PASSWORD: timeout
