api_center:
    resource: '../../src/App/Center/'
    type: annotation
    prefix: '/api'
    requirements:
        _format: 'json'

api_sport:
    resource: '../../src/App/Sport/'
    type: annotation
    prefix: '/api'
    requirements:
        _format: 'json'
